import type {
  Category,
  Effect,
  EffectCondition,
  GameContent,
  PressureId,
  ResourceId,
  TraitDefinition,
} from './types'

const pressure = (target: PressureId, amount: number, when?: EffectCondition): Effect => ({
  type: 'pressure',
  target,
  amount,
  when,
})
const harvest = (target: ResourceId, amount: number): Effect => ({
  type: 'harvest',
  target,
  amount,
})
const births = (amount: number, when?: EffectCondition): Effect => ({
  type: 'births',
  amount,
  when,
})
const cold = { temperature: 'cold' } as const
const hot = { temperature: 'hot' } as const

function trait(
  id: string,
  name: string,
  category: Category,
  cost: number,
  tags: string[],
  description: string,
  effects: Effect[],
  permanentName: string,
  permanentEffects: Effect[],
  rewardPool = true,
): TraitDefinition {
  return {
    id,
    name,
    category,
    cost,
    tags,
    description,
    effects,
    permanent: { name: permanentName, effects: permanentEffects },
    rewardPool,
  }
}

const traits: TraitDefinition[] = [
  trait(
    'small-body',
    '小型体型',
    'morphology',
    1,
    ['small', 'efficient'],
    '较少的食物也能维持生存，但身体容易散热。',
    [pressure('food', -2), pressure('predation', -1), pressure('temperature', 1, cold)],
    '小型化',
    [pressure('food', -1), pressure('predation', -1), pressure('temperature', 1, cold)],
  ),
  trait(
    'forelimbs',
    '灵活前肢',
    'morphology',
    1,
    ['limbs'],
    '攀爬、采集与逃脱的起点，可向三种方向突变。',
    [pressure('predation', -2), harvest('plants', 2)],
    '灵活肢体',
    [pressure('predation', -1), harvest('plants', 1)],
  ),
  trait(
    'wings',
    '翼',
    'morphology',
    2,
    ['limbs', 'aerial'],
    '离开地面捕食者的范围，飞行需要额外食物。',
    [pressure('predation', -6), pressure('temperature', -2, hot), pressure('food', 2)],
    '飞行能力',
    [pressure('predation', -3), pressure('temperature', -1, hot), pressure('food', 1)],
    false,
  ),
  trait(
    'claws',
    '利爪',
    'morphology',
    1,
    ['limbs', 'hunting'],
    '捕获小型动物，代价是更高的日常消耗。',
    [harvest('animals', 4), pressure('predation', -1), pressure('food', 1)],
    '爪化前肢',
    [harvest('animals', 2), pressure('food', 1)],
    false,
  ),
  trait(
    'digging-limbs',
    '挖掘肢',
    'morphology',
    2,
    ['limbs', 'underground'],
    '地下空间隔绝极端温度，也减少捕食风险。',
    [pressure('temperature', -5), pressure('predation', -3), pressure('food', 1)],
    '地下生活',
    [pressure('temperature', -2), pressure('predation', -2), pressure('food', 1)],
    false,
  ),
  trait(
    'shell',
    '厚重甲壳',
    'morphology',
    2,
    ['armored'],
    '坚固防护需要营养投入，也降低繁殖速度。',
    [pressure('predation', -7), pressure('food', 1), births(-2)],
    '甲壳化',
    [pressure('predation', -3), pressure('food', 1), births(-1)],
  ),

  trait(
    'coat',
    '体毛',
    'physiology',
    1,
    ['insulation'],
    '适应森林的凉意，却可能成为草原上的负担。',
    [pressure('temperature', -4, cold), pressure('temperature', 1, hot)],
    '毛被',
    [pressure('temperature', -2, cold), pressure('temperature', 1, hot)],
  ),
  trait(
    'thick-fur',
    '厚毛',
    'physiology',
    2,
    ['insulation'],
    '高度保温，面对高温时难以散热。',
    [pressure('temperature', -8, cold), pressure('temperature', 3, hot)],
    '厚密毛被',
    [pressure('temperature', -4, cold), pressure('temperature', 2, hot)],
    false,
  ),
  trait(
    'sparse-fur',
    '稀疏体毛',
    'physiology',
    1,
    ['cooling'],
    '用寒冷中的脆弱换取更好的散热。',
    [pressure('temperature', -4, hot), pressure('temperature', 2, cold)],
    '散热皮肤',
    [pressure('temperature', -2, hot), pressure('temperature', 1, cold)],
    false,
  ),
  trait(
    'fat-storage',
    '储脂',
    'physiology',
    1,
    ['efficient', 'insulation'],
    '储备缓解短缺与寒冷，但挤占繁殖投入。',
    [pressure('food', -3), pressure('temperature', -2, cold), births(-1)],
    '脂肪储备',
    [pressure('food', -2), births(-1)],
  ),
  trait(
    'low-metabolism',
    '低代谢',
    'physiology',
    1,
    ['efficient'],
    '降低生存所需，也放慢谱系增长。',
    [pressure('food', -4), births(-2)],
    '节能生理',
    [pressure('food', -2), births(-1)],
  ),
  trait(
    'heat-tolerance',
    '高效散热',
    'physiology',
    1,
    ['cooling'],
    '主动散热需要额外能量。',
    [pressure('temperature', -5, hot), pressure('food', 1)],
    '耐热体质',
    [pressure('temperature', -3, hot), pressure('food', 1)],
  ),

  trait(
    'burrow',
    '挖洞',
    'behavior',
    1,
    ['underground'],
    '用繁殖时间换取洞穴中的稳定与安全。',
    [pressure('temperature', -3), pressure('predation', -2), births(-1)],
    '穴居性',
    [pressure('temperature', -2), pressure('predation', -1), births(-1)],
  ),
  trait(
    'nocturnal',
    '夜行',
    'behavior',
    1,
    ['nocturnal', 'cooling'],
    '避开白天的酷热与捕食者，觅食更困难。',
    [pressure('temperature', -3, hot), pressure('predation', -2), pressure('food', 1)],
    '夜行习性',
    [pressure('temperature', -2, hot), pressure('predation', -1), pressure('food', 1)],
  ),
  trait(
    'herd',
    '群居',
    'behavior',
    1,
    ['social'],
    '共同警戒减少捕食，群体也消耗更多食物。',
    [pressure('predation', -4), pressure('food', 1)],
    '群体生活',
    [pressure('predation', -2), pressure('food', 1)],
  ),
  trait(
    'hibernate',
    '冬眠',
    'behavior',
    2,
    ['efficient', 'insulation'],
    '减少饥饿与寒冷影响，暂停一部分繁殖。',
    [pressure('food', -6), pressure('temperature', -4, cold), births(-4)],
    '休眠习性',
    [pressure('food', -3), pressure('temperature', -2, cold), births(-2)],
  ),
  trait(
    'store-food',
    '储藏食物',
    'behavior',
    1,
    ['gathering'],
    '更充分地利用本代资源，投入一部分育幼时间。',
    [harvest('plants', 4), harvest('insects', 1), births(-1)],
    '储食习性',
    [harvest('plants', 2), births(-1)],
  ),
  trait(
    'ambush',
    '伏击',
    'behavior',
    1,
    ['hunting'],
    '捕获猎物时也会暴露给更大的捕食者。',
    [harvest('animals', 5), pressure('predation', 1)],
    '伏击习性',
    [harvest('animals', 3), pressure('predation', 1)],
  ),

  trait(
    'omnivore',
    '杂食',
    'diet',
    1,
    ['gathering', 'generalist'],
    '从三类资源中各取所需，适应资源变化。',
    [harvest('plants', 2), harvest('insects', 2), harvest('animals', 1)],
    '杂食性',
    [harvest('plants', 1), harvest('insects', 1)],
  ),
  trait(
    'grazer',
    '食草',
    'diet',
    1,
    ['gathering', 'herbivore'],
    '大量利用植物，但开阔地觅食增加风险。',
    [harvest('plants', 6), pressure('predation', 1)],
    '植食性',
    [harvest('plants', 3), pressure('predation', 1)],
  ),
  trait(
    'insectivore',
    '食虫',
    'diet',
    1,
    ['gathering', 'insectivore'],
    '高效利用昆虫资源；资源枯竭时收益有限。',
    [harvest('insects', 5)],
    '食虫性',
    [harvest('insects', 2)],
  ),
  trait(
    'scavenger',
    '食腐',
    'diet',
    1,
    ['hunting', 'scavenger'],
    '利用动物残余，营养质量影响后代数量。',
    [harvest('animals', 4), births(-1)],
    '食腐性',
    [harvest('animals', 2), births(-1)],
  ),
  trait(
    'roots',
    '挖掘根茎',
    'diet',
    1,
    ['gathering', 'underground'],
    '隐蔽地利用植物根茎，采集耗费育幼时间。',
    [harvest('plants', 4), pressure('predation', -2), births(-1)],
    '根茎食性',
    [harvest('plants', 2), pressure('predation', -1), births(-1)],
  ),
  trait(
    'hunter',
    '主动捕猎',
    'diet',
    2,
    ['hunting'],
    '充分利用动物资源，维持狩猎能力需要食物。',
    [harvest('animals', 8), pressure('predation', -2), pressure('food', 2)],
    '捕食性',
    [harvest('animals', 4), pressure('food', 1)],
  ),

  trait(
    'early-maturity',
    '快速成熟',
    'reproduction',
    1,
    ['fertile'],
    '提前繁殖，也提高食物需求。',
    [births(4), pressure('food', 1)],
    '早熟',
    [births(2), pressure('food', 1)],
  ),
  trait(
    'many-offspring',
    '大量后代',
    'reproduction',
    1,
    ['fertile'],
    '以更多出生应对损失，需要充足资源。',
    [births(7), pressure('food', 2)],
    '高繁殖率',
    [births(4), pressure('food', 2)],
    false,
  ),
  trait(
    'parental-care',
    '精细育幼',
    'reproduction',
    2,
    ['social', 'care'],
    '保护后代、提高存活，增加营养投入。',
    [births(5), pressure('predation', -2), pressure('food', 1)],
    '育幼习性',
    [births(3), pressure('food', 1)],
    false,
  ),
  trait(
    'seasonal-breeding',
    '集中繁殖',
    'reproduction',
    1,
    ['fertile'],
    '同步繁殖带来更多后代，也吸引捕食者。',
    [births(5), pressure('predation', 1)],
    '繁殖季',
    [births(2), pressure('predation', 1)],
  ),
  trait(
    'long-life',
    '长寿',
    'reproduction',
    1,
    ['efficient'],
    '降低风险与消耗，但繁殖较慢。',
    [births(-2), pressure('predation', -2), pressure('food', -1)],
    '长寿谱系',
    [births(-1), pressure('predation', -1), pressure('food', -1)],
  ),
  trait(
    'communal-nursery',
    '共同育幼',
    'reproduction',
    1,
    ['care'],
    '已有群居性状时，协作能保护更多后代。',
    [births(4), births(2, { tags: ['social'] }), pressure('food', 1)],
    '协作育幼',
    [births(2), births(1, { tags: ['social'] }), pressure('food', 1)],
  ),
]

export const content: GameContent = {
  version: '1',
  ancestorName: '原始小型四足动物',
  traits: Object.fromEntries(traits.map((definition) => [definition.id, definition])),
  startingDeck: [
    'omnivore',
    'omnivore',
    'burrow',
    'burrow',
    'small-body',
    'forelimbs',
    'coat',
    'early-maturity',
    'insectivore',
    'herd',
  ],
  rules: {
    initialPopulation: 120,
    handSize: 5,
    expressionBudget: 3,
    fixationThreshold: 5,
    permanentLimit: 6,
    rewardInterval: 2,
    baseBirths: 8,
    foodBirthPenalty: 1,
    deathRates: { food: 2, temperature: 2, predation: 2 },
    maxPressure: 10,
    maxResource: 10,
  },
  environments: [
    {
      id: 'forest',
      name: '森林',
      description: '资源充足，凉意与林间捕食者考验最初的适应。',
      duration: 8,
      temperature: 'cold',
      stages: [
        {
          fromGeneration: 1,
          name: '林下生存',
          pressures: { food: 5, temperature: 2, predation: 3 },
          resources: { plants: 8, insects: 6, animals: 4 },
        },
      ],
      eventIds: ['quiet', 'fruiting', 'cold-snap', 'predators'],
    },
    {
      id: 'grassland',
      name: '草原',
      description: '开阔地带更炎热，食物分布也开始变化。',
      duration: 8,
      temperature: 'hot',
      stages: [
        {
          fromGeneration: 1,
          name: '开阔生态位',
          pressures: { food: 7, temperature: 5, predation: 5 },
          resources: { plants: 6, insects: 5, animals: 5 },
        },
      ],
      eventIds: ['quiet', 'heat-wave', 'migration', 'predators'],
    },
    {
      id: 'drought',
      name: '干旱期',
      description: '资源逐步枯竭。让谱系穿过最后八个世代。',
      duration: 8,
      temperature: 'hot',
      stages: [
        {
          fromGeneration: 1,
          name: '旱季来临',
          pressures: { food: 8, temperature: 7, predation: 5 },
          resources: { plants: 4, insects: 4, animals: 3 },
        },
        {
          fromGeneration: 4,
          name: '旱情加重',
          pressures: { food: 9, temperature: 8, predation: 6 },
          resources: { plants: 3, insects: 3, animals: 3 },
        },
        {
          fromGeneration: 7,
          name: '极端干旱',
          pressures: { food: 10, temperature: 10, predation: 6 },
          resources: { plants: 2, insects: 2, animals: 2 },
        },
      ],
      eventIds: ['quiet', 'heat-wave', 'scarcity', 'migration'],
    },
  ],
  events: {
    quiet: {
      id: 'quiet',
      name: '短暂平稳',
      description: '本代没有额外环境变化。',
      flavor: '这一代风平浪静。威胁只来自环境本身，而不是意外。',
    },
    fruiting: {
      id: 'fruiting',
      name: '果实丰收',
      description: '植物资源 +2，食物压力 −1。',
      flavor: '林间果实成熟，会采集的物种第一次尝到了富足。',
      resources: { plants: 2 },
      pressures: { food: -1 },
    },
    'cold-snap': {
      id: 'cold-snap',
      name: '林间寒潮',
      description: '寒冷压力 +1。',
      flavor: '气温骤降，缺乏御寒能力的个体正在大量死亡。',
      pressures: { temperature: 1 },
    },
    predators: {
      id: 'predators',
      name: '捕食者巡游',
      description: '捕食压力 +1。',
      flavor: '捕食者在领地中频繁巡游，落单的个体最先消失。',
      pressures: { predation: 1 },
    },
    'heat-wave': {
      id: 'heat-wave',
      name: '热浪',
      description: '高温压力 +1，上限 10。',
      flavor: '热浪压过开阔地，散热能力决定了谁能撑到黄昏。',
      pressures: { temperature: 1 },
    },
    migration: {
      id: 'migration',
      name: '小型动物迁入',
      description: '小型动物资源 +2，捕食压力 −1。',
      flavor: '一群小型动物迁入这片土地，猎物变多了，捕食者也跟着离开。',
      resources: { animals: 2 },
      pressures: { predation: -1 },
    },
    scarcity: {
      id: 'scarcity',
      name: '植物枯萎',
      description: '植物资源 −1，食物压力 +1，上限 10。',
      flavor: '植物成片枯萎，可采集的食物正在减少。',
      resources: { plants: -1 },
      pressures: { food: 1 },
    },
  },
  mutations: [
    {
      id: 'limbs-wings',
      from: 'forelimbs',
      to: 'wings',
      description: '前肢走向飞行，承担额外能量消耗。',
    },
    { id: 'limbs-claws', from: 'forelimbs', to: 'claws', description: '前肢转向捕获动物资源。' },
    {
      id: 'limbs-digging',
      from: 'forelimbs',
      to: 'digging-limbs',
      description: '前肢转向地下生态位。',
    },
    {
      id: 'coat-thick',
      from: 'coat',
      to: 'thick-fur',
      description: '毛被更厚，适应严寒却惧怕酷热。',
    },
    { id: 'coat-sparse', from: 'coat', to: 'sparse-fur', description: '减少体毛，适应炎热环境。' },
    {
      id: 'maturity-many',
      from: 'early-maturity',
      to: 'many-offspring',
      description: '走向数量型繁殖策略。',
    },
    {
      id: 'maturity-care',
      from: 'early-maturity',
      to: 'parental-care',
      description: '走向投入型繁殖策略。',
    },
  ],
}
